const products = [
  {name:'Compact Travel Charger',category:'Tech',retailer:'Temu-ready listing',icon:'🔌',price:'Add verified price',tip:'Replace with a verified GaN charger listing and compatibility details.',color:'linear-gradient(135deg,#e8e0ff,#c9bbff)'},
  {name:'Wireless Audio Find',category:'Tech',retailer:'Crazy Eddie archive idea',icon:'🎧',price:'Add verified price',tip:'Use only a current, legitimate retailer link—not an unverified legacy offer.',color:'linear-gradient(135deg,#ffe0ee,#ffc3dd)'},
  {name:'Smart Desk Upgrade',category:'Tech',retailer:'Temu-ready listing',icon:'🖥️',price:'Add verified price',tip:'Add dimensions, device compatibility, and one practical buyer tip.',color:'linear-gradient(135deg,#dcecff,#add5ff)'},
  {name:'Kitchen Helper',category:'Home',retailer:'Weis-ready listing',icon:'🍳',price:'Add verified price',tip:'Confirm whether this is stocked online or in a shopper’s local store.',color:'linear-gradient(135deg,#fff0ce,#ffdda1)'},
  {name:'Home Organizer',category:'Home',retailer:'Temu-ready listing',icon:'🧺',price:'Add verified price',tip:'List measurements so shoppers can confirm it fits their space.',color:'linear-gradient(135deg,#dffff0,#aef1cf)'},
  {name:'Everyday Value Pick',category:'Everyday',retailer:'Weis-ready listing',icon:'🛍️',price:'Add verified price',tip:'Swap in a current weekly find with accurate dates and terms.',color:'linear-gradient(135deg,#fff1de,#ffcfa8)'}
];
const grid=document.querySelector('#product-grid'),search=document.querySelector('#search'),empty=document.querySelector('#empty-state');let active='all';
function render(){const q=search.value.trim().toLowerCase();const shown=products.filter(p=>(active==='all'||p.category===active)&&(`${p.name} ${p.category} ${p.retailer} ${p.tip}`.toLowerCase().includes(q)));grid.innerHTML=shown.map(p=>`<article class="product-card"><div class="product-visual" style="--visual:${p.color}"><span class="retailer-badge">${p.retailer}</span><span aria-hidden="true">${p.icon}</span></div><div class="product-body"><span class="category">${p.category}</span><h3>${p.name}</h3><p>${p.tip}</p><div class="price-line"><span class="price">${p.price}</span><a class="product-link" href="#about" aria-label="Review listing guidance for ${p.name}">Review →</a></div></div></article>`).join('');empty.hidden=shown.length>0}
document.querySelectorAll('.filter').forEach(b=>b.addEventListener('click',()=>{document.querySelector('.filter.active').classList.remove('active');b.classList.add('active');active=b.dataset.filter;render()}));search.addEventListener('input',render);
const theme=document.querySelector('.theme-button');theme.addEventListener('click',()=>{document.body.classList.toggle('dark');const dark=document.body.classList.contains('dark');theme.textContent=dark?'☀':'☾';theme.setAttribute('aria-label',dark?'Switch to light theme':'Switch to dark theme')});
const menu=document.querySelector('.menu-button'),nav=document.querySelector('#site-nav');menu.addEventListener('click',()=>{const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',String(open))});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');menu.setAttribute('aria-expanded','false')}));
document.querySelector('#year').textContent=new Date().getFullYear();render();
